"""sphere github columns

Revision ID: 577d34871cbf
Revises: 5f02cbceeb7d
Create Date: 2026-02-25 07:24:13.408558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '577d34871cbf'
down_revision: Union[str, None] = '5f02cbceeb7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('sphere', sa.String(length=64), nullable=False))
    op.add_column('student_profiles', sa.Column('sphere', sa.String(length=64), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_profiles', 'sphere')
    op.drop_column('jobs', 'sphere')
    # ### end Alembic commands ###
